### ISSUE TITLE
Support DBT unit tests

### ISSUE THREAD

**Issue by andrew-cybsafe** [vim-test/vim-test#812]
DBT has recently added support for [unit tests](https://docs.getdbt.com/docs/build/unit-tests). These are stored in yaml files within the DBT project directory structure in the following form:

```
unit_tests:
  - name: model1_test
    model: model1
    ...

  - name: model2_test
    model: model2
    ...
```

To target these unit test directly, you run the command:
```
dbt test --select "unit_test:{project_name}:{test_name}
# i.e. for project my_project:
dbt test --select "unit_test:my_project:model1_test"
```

I see a few challenges in implementing this, including:
- test strategy is based on file type, and the file type here will be 'yaml' (i.e. not specific to DBT)
- determining the project name. To do this we'll need to dive down the directory structure to find a dbt_project.yml file in which there is a name attribute
- Supporting full file testing is awkward as DBT doesn't support running tests based on the containing file name. Perhaps we should only support TestNearest for now

Thoughts on how best to tackle these?
